---
title: "Syllabus: MGMT 30500: Business Statistics"
subtitle: "Mitchell E. Daniels, Jr. School of Business, Purdue University"
# date-modified: "last-modified"
date: "2024-08-01"
date-format: "MMM D, YYYY"
#listing:
# - id: schedule
#   contents:
#      - topics/topic-*.qmd
#    type: table
#    fields: [title, subtitle, date]
#    field-display-names:
#      title: "Topic"
#      description: "Dates"
#      subtitle: "Topics"
#    date-format: "MMMM DD, YYYY"
#    sort: [filename]
#    sort-ui: false
#    filter-ui: false
---

<br>
<center>
_IMPORTANT_

_This document does not replace the official syllabus in the course brightspace page_

</center>
<br>

## Course Description

The course is designed to introduce students to basic data analysis techniques.  Coverage will include the application of probability distributions such as the normal, the $t$, and the binomial; sampling distributions, basic statistical inference methods, analysis of variance, applied linear regression techniques, logistic regression time series analysis, statistical quality control, and decision analysis.

**Class:** Section 13:  MWF (9:30 am – 10:20 am), RAWL 3082	

**Course Website**: <https://davi-moreira.github.io/2024F_business_statistics_purdue_MGMT305>{target="_blank"}

## Instructor 

### Instructor: [Professor Davi Moreira](https://davi-moreira.github.io)

-   Email: [dmoreira\@purdue.edu](mailto:dmoreira@purdue.edu)

-   Virtual Office hours - _Zoom link in your Course Brightspace Page_: 

## Learning Outcomes

By the end of this course, students will be able to:

1.	Understand the basic statistical principles and their applications in the area of management and business.
2.	Understand fundamental issues in business and management.
3.	Describe and use the commonly used statistical techniques for analyzing business data.
4.	Understand the impacts of recent developments in big data and AI in business and management.
5.	Be proficient in using Excel to carry out statistical and analytics methods covered in the course.

## Objectives

Our main goal is to instill the basic quantitative and data analysis skills needed by managers in modern business, where Business Analytics and Data Science have become important. These skills will help managers to understand and carry out data-based decision making, risk assessments, and policy making and to work effectively with data analysis teams to improve all aspects of business performance.
	
Modern data analysis is done using computers and various types of sophisticated software. Therefore, to most effectively introduce management candidates to its techniques, we will also emphasize software applications (with Microsoft Excel, R, or Python) in this course.   

### Course Materials

The following are learning materials:

1. Text book:  Anderson, Sweeney, Williams, Camn, Cochran, Fry, and Ohlmann: Modern Business Statistics with Microsoft Excel, 7th edition, 2018, Cengage Learning, Inc. (Required)  This text is also used in STAT 30301.

2. Handouts:  Lecture Slides and Supplementary Materials. (Posted in this page and on Brightspace: Brightspace -> Content -> Table of Contents -> ….)

### Course Infra-structure

**Brightspace:** The Course Brightspace Page <https://purdue.brightspace.com/> should be checked on a regular basis for announcements and course material.

**Software:** Microsoft Excel will be used for in-class demonstrations and instruction. The main tool is Data Analysis under Tools.  If you don’t see this tool, follow the following steps to add in:
-   File > Options -> Add-ins -> Select Analysis ToolPak and Analysis ToolPak-VBA (also select StatTools 7.5, if available) -> Go -> Data -> Data Analysis (to conduct analyses)

**Course Website:** This class website will be used throughout the course, but it does not replace the Course Brightspace Page.

## Assessments

### Grading 

Following a university-wide initiative, the School has adopted an Official Grading Policy for core courses such as MGMT 30500.  Under this policy, the overall GPA for this class can be no higher than 3.0. To comply with this course policy, final course letter grades will be based on the curved class final course percentages. The final course percentage is based on a weighted percentage computed using the weights shown in the table below:

| **Assignment**             | **Percentage** |
|----------------------------|:--------------:|
| Homework*                  |      40%       |
| Quizzes**                  |      15%       |
| Midterms***                |      15%       |
| Attendance/Participation   |       7%       |
| Final****                  |      13%       |

\*There are eight homework assignments. No homework assignment is dropped. The final homework score is calculated using aggregated points.

\** There are three quizzes worth 5% each. Quizzes 2 and 3 are not cumulative. 

\***There are two midterms: each is worth 7.5%. Midterms are not cumulative.

\**** Final is cumulative.

### Homework 

There are eight Homework Assignments – check the due dates in the schedule. Each Homework Assignment contains 

- Part A: Exercise problems from the text;

- Part B: Supplementary problems.
      
      _Please note:  Homework is accepted only by being properly and timely uploaded to Brightspace.  Homework is not accepted late or in any other way, including by email, for any reason. Also, all students must be assessed on the same work so ad-hoc extra-credit or makeup assignments will not be given._ 
      
Brightspace will be set to allow you 2 chances to submit the assignment.  If you submit twice, only your second submission will be graded.  The first will not be looked at. 

**Make sure to upload only one file (pdf) for each homework assignment**. No supplements, attachments, or appendices can be used.  

**Important**: You must include all relevant software output that addresses the homework questions and reference it clearly where appropriate. Copy and paste all software output that addresses the homework questions into your homework papers, and reference it clearly where appropriate, but do not copy and paste any datasets into your homework papers.

If an exercise instructs you to do a computation by hand, you do not have to include the by-hand work in your homework paper.  This makes it easier to turn your work in online to Brightspace.  However, you should make sure that you can do the by-hand computation by checking your answer against Excel’s result.  You will need to do the by-hand computations on exams so, again, make sure you know how to do them.  

In your submissions, homework problems must be clearly identified by their respective chapter and problem numbers.

Your proficiency in this course will improve if these problems are done faithfully and in a timely fashion. Try not to wait until the last minute to do your homework.  

You may discuss the homework problems with classmates, but DO NOT COPY. You are expected to write your homework individually. Duplicate papers are considered cheating.   

Your homework submissions are graded by the course graders. If you have any issues about the grading, please refer to the paragraph, Grade Challenges, below.

### Quizzes

To encourage students to work steadily through the materials, three quizzes are given. Quizzes 2 and 3 are not cumulative. The quizzes will each count for 5% of the final course percentage and none are dropped. Only under exceptional circumstances, when legitimate and verifiable reasons are provided, will make-ups be given. “Exceptional circumstances” means a death in the family, a serious personal medical emergency, participation in a conflicting NCAA athletic event, or as otherwise required by University policies.  Except for emergencies, requests for a makeup must be made by email with supporting documentation no later than 7 days before the scheduled quiz.

### Exams

Exams will test both technical abilities to carry out standard calculations and your understanding of important concepts. Exams are closely based on homework exercises and sample exams. Exams and homework are designed to assess different types and levels of understanding. There will be two Midterms (each is worth 7.5% of the total grade) and a Final (23% of the total grade), all given in-person. The second Midterm is not cumulative. The Final is cumulative.  You will need a calculator for taking exams. Calculators that have USB ports or can access the internet are not permitted nor are you allowed to use a smart phone or watch as a calculator.  You are required to take all exams.  (None are dropped.)  Only under exceptional circumstances, when legitimate and verifiable reasons are provided, will make-ups be given. “Exceptional circumstances” means a death in the family, a serious personal medical emergency, participation in a conflicting NCAA athletic event, or as otherwise required by University policies.  Except for emergencies, requests for a makeup must be made by email with supporting documentation no later than 7 days before the scheduled exam.

Attendance and Participation: Attend your classes, pay attention and participate.  If you do not attend class, you will likely not succeed. According to the University regulations (<https://catalog.purdue.edu/content.php?catoid=15&navoid=18634#classes>), “Scheduled courses allow students to avoid conflicts and reflect the University’s expectation that students should be present for every meeting of a class/laboratory for which they are registered.” The instructor will take random attendance and keep the attendance record. Your attendance/participation grade will be based on this record.

### Grade Challenges  

When grades are posted in the Brightspace Grade Center, an announcement will be posted on Brightspace. Any challenge to any grade must be made within 7 calendar days of the posting of the announcement. There is one exception: to facilitate the computation of final course grades, the last homework assignment must be challenged within three days of the posting of grades.  Grade challenges must be based on good faith disputes about mathematical or statistical principles.  They cannot be based on post-hoc legalistic arguments.

To challenge a homework score, quiz score or exam score, you must send the instructor an email describing your challenge.  Include your name, ID, and Assignment Number. Please note: General grade reviews for homework are not done. For homework, the challenge must cite the instructor to a specific deduction and provide a reason it is believed to be incorrect. Please check the Homework Solutions on Brightspace before submitting a homework grade challenge. Most often, the Homework Solutions will provide the basis for the deduction(s). Grades will not be discussed in the classroom during, between, or after classes.   

**After the 7 day challenge period, all grades are final for purposes of calculating the final course grade.**   

## KEYS TO SUCCESS 

You will succeed in this course if you adhere to the following:

1.	Consistent Effort: Follow the schedule outlined in the Course Outline diligently.
2.	Pre-Class Preparation: 
    a. Read the lecture material and annotations before your scheduled class. Refer to the Course Schedule to determine the appropriate chapter to read. The readings are typically brief, especially considering the included tables and figures.
    b. Review the homework exercises for the relevant chapter before class. These exercises will be the primary focus during class sessions.
3.	Class Materials: 
    a. Either print the readings, annotations, and homework exercises, or ensure you have them accessible on your laptop or tablet. This will allow you to take notes directly on the materials during class.
4.	Engagement with Problems:
    a. Understanding statistics and data analysis requires exposure to numerous examples and practice with many problems. It is crucial to recognize that this course may differ from others: even if you comprehend the lectures and readings, you may initially struggle with the problems.
    b. Make an effort to solve the assigned homework problems independently. Continuously work on the chapter problems as the course progresses. Regular practice, particularly after each chapter lecture, will help you master the problems.
5.	Active Learning:
    a. Adhering to these procedures is essential for success in this class. Relying solely on in-class presentations without engaging with the course materials will likely result in difficulties.   

<!---
## Grading

Each student’s final grade will be based on the following after rounding up to the nearest point:

| Grade | Range       |
|-------|-------------|
| A     | 95% -- 100% |
| A-    | 90% -- 94%  |
| B+    | 85% -- 89%  |
| B     | 80% -- 84%  |
| B-    | 75% -- 79%  |
| C     | 65% -- 74%  |
| D     | 60% -- 64%  |
| F     | \< 60%      |
--->

## AI policy

I encourage you to use AI tools you believe will enhance your individual or group learning performance. Learning to use AI is a valuable and emerging skill, and I am available to provide support and assistance with these tools during office hours or by appointment.

Be aware of the following guidelines:

- You are **not** allowed to use AI tools during the exams.

- Providing low-effort prompts will result in low-quality outputs. You must refine your prompts to achieve desirable outcomes. Use the course knowledge for that!

- Make the AI tool help you in your learning process. Do not ask for solutions, ask for explanations, for examples, present your doubts about a topic, and interact and with it!

- Do not blindly trust the information provided by the output. Any errors or omissions resulting from using the AI tool will be your responsibility. Remember, the AI tool works better for topics that you already understand.

- While AI is a tool, you must acknowledge its use. Always cite! Include a short note at the end of any document to mention that you used AI in its development.

## Deadlines 

The Registrar's add, drop, and modify deadline dates for this semester are at the following website: <http://www.purdue.edu/Registrar/>

## Academic Integrity  

Please refer the University Policies on Brightspace.

## Accessibility and Accommodations:

Purdue University strives to make learning experiences as accessible as possible. If you anticipate or experience physical or academic barriers based on disability, please let me know so that we can discuss options. You are also encouraged to contact the Disability Resource Center at: <drc@purdue.edu> or by phone: 765-494-1247.

-   CAPS Information:   Purdue University is committed to advancing the mental health and well-being of its students. If you or someone you know is feeling overwhelmed, depressed, and/or in need of support, services are available. For help, such individuals should contact Counseling and Psychological Services (CAPS) at 765-494-6995 and <http://www.purdue.edu/caps/> during and after hours, on weekends and holidays, or through its counselors physically located in the Purdue University Student Health Center (PUSH) during business hours.

## Non-Discrimination Statement: 

Please refer to the Nondiscrimination Statement on Brightspace.

## Emergency Situation(s): 

Please refer to the Emergency Preparedness on Brightspace.

## Subject to Change Policy

While I will try to adhere to the course schedule as much as possible, I also want to adapt to your learning pace and style. The syllabus and course plan may change in the semester.

## [Schedule](./schedule.qmd)